# fly.toml app configuration file generated for divizend-ipfs on 2025-04-21T02:52:34+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'divizend-ipfs'
primary_region = 'fra'

[build]

[env]
  IPFS_PROFILE = "server"
  IPFS_PATH = '/data/ipfs'

[[mounts]]
  source = 'ipfs_data'
  destination = '/data/ipfs'

[services]
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 8080
    force_https = true

  [[services.ports]]
    port = 4001
    protocol = "tcp"

  [[services.ports]]
    port = 5001
    protocol = "tcp"

  [[services.tcp_checks]]
    port = 4001
    interval = "15s"
    timeout = "2s"

  [[services.tcp_checks]]
    port = 5001
    interval = "15s"
    timeout = "2s"

  [[services.http_checks]]
    port = 5001
    path = "/webui"
    interval = "30s"
    timeout = "5s"
  
  [services.concurrency]
    type = 'connections'
    hard_limit = 50
    soft_limit = 25

[checks]
  [checks.httpcheck]
    type = "http"
    interval = "30s"
    timeout = "5s"
    port = 5001
    path = "/webui"

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
