app = 'divizend-ipfs'
primary_region = 'fra'

[build]
  dockerfile = 'Dockerfile'

[env]
  IPFS_PATH = '/data/ipfs'
  IPFS_PROFILE = 'server'

[[mounts]]
  source = 'ipfs_data'
  destination = '/data/ipfs'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 5001
  [[services.ports]]
    port = 5001
  [services.concurrency]
    type = 'connections'
    hard_limit = 50
    soft_limit = 25
  [[services.http_checks]]
    interval = '30s'
    timeout = '5s'
    path = '/api/v0/version'
    port = 5001

[[services]]
  protocol = 'tcp'
  internal_port = 4001
  [[services.ports]]
    port = 4001
  [services.concurrency]
    type = 'connections'
    hard_limit = 50
    soft_limit = 25
  [[services.tcp_checks]]
    interval = '15s'
    timeout = '2s'

[[services]]
  protocol = 'udp'
  internal_port = 4001
  [[services.ports]]
    port = 4001
  [services.concurrency]
    type = 'connections'
    hard_limit = 50
    soft_limit = 25

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'

[checks]
  [checks.api]
    port = 5001
    type = 'http'
    interval = '30s'
    timeout = '5s'
    path = '/api/v0/version'