# fly.toml app configuration file generated for divizend-ipfs on 2025-04-21T03:17:08+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'divizend-ipfs'
primary_region = 'fra'

[build]

[env]
  IPFS_PATH = '/data/ipfs'
  IPFS_PROFILE = 'server'

[[mounts]]
  source = 'ipfs_data'
  destination = '/data/ipfs'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = ''
  internal_port = 0

  [[services.ports]]
    port = 8080
    handlers = ['tls', 'http']

  [[services.ports]]
    port = 4001

  [[services.ports]]
    port = 5001

  [services.concurrency]
    type = 'connections'
    hard_limit = 50
    soft_limit = 25

  [[services.tcp_checks]]
    interval = '15s'
    timeout = '2s'

  [[services.tcp_checks]]
    interval = '15s'
    timeout = '2s'

  [[services.http_checks]]
    interval = '30s'
    timeout = '5s'
    path = '/webui'

[checks]
  [checks.httpcheck]
    port = 5001
    type = 'http'
    interval = '30s'
    timeout = '5s'
    path = '/webui'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
